[package]
name = "rust_embedded_lib"
version = "0.1.0"

[lib]
name = "rust_embedded_lib"
path = "src/lib.rs"
# crate-type = ["cdylib"]      # Creates dynamic lib
crate-type = ["staticlib"] # Creates static lib

[dependencies]
cty = "0.2.2"

[build-dependencies]
bindgen = "0.64.0"
